# Generated by Django 5.0.7 on 2024-09-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_blogpost_id_delete_profilepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
