# Generated by Django 5.0.7 on 2024-09-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
    ]
