# Generated by Django 5.0.7 on 2024-09-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_tasks_rename_blogpost_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
