# Generated by Django 5.0.7 on 2024-09-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_alter_tasks_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
