# Generated by Django 5.0.7 on 2024-09-18 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_alter_projects_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
    ]
