# Generated by Django 5.0.7 on 2024-09-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_projects_user_alter_projects_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
    ]
