# Generated by Django 5.0.7 on 2024-09-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_projects_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
