# Generated by Django 5.0.7 on 2024-09-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0033_alter_projects_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
