# Generated by Django 5.0.7 on 2024-09-18 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0034_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
