# Generated by Django 5.0.7 on 2024-09-18 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0036_alter_projects_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
