# Generated by Django 5.0.7 on 2024-09-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_remove_projects_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
